#!/bin/bash
file="scenario-2-firewall-config-v6-FULL.html"
echo "# Scenario 2: Firewall Configuration - Workflow Checklist Validation"
echo ""
echo "## Initial Intake"
grep -q "FW-8823" $file && echo "- [x] Ticket ID present (#FW-8823)" || echo "- [ ] Ticket ID missing"
grep -q "John.*Finance" $file && echo "- [x] User and problem identified" || echo "- [ ] User/problem missing"
grep -q "IO_AGENT.*Receives" $file && echo "- [x] IO agent picks up ticket" || echo "- [ ] IO pickup missing"
grep -q "Q1:\|Q2:\|Q3:\|Q4:\|Q5:" $file && echo "- [x] IO agent asks 5 questions" || echo "- [ ] Questions missing"
grep -q "Problem Classification" $file && echo "- [x] Problem type determined" || echo "- [ ] Classification missing"
echo ""
echo "## MRA Orchestration"
grep -q "MRA\|MASTER_REASONING" $file && echo "- [x] MRA deployed" || echo "- [ ] MRA missing"
grep -q "KNOWLEDGE_GRAPH\|Knowledge Graph" $file && echo "- [x] KG queries present" || echo "- [ ] KG missing"
grep -q "RAG.*SYSTEM\|RAG.*quer" $file && echo "- [x] RAG queries present" || echo "- [ ] RAG missing"
grep -q "Three-Source" $file && echo "- [x] Three-Source Analysis" || echo "- [ ] Analysis missing"
echo ""
echo "## Specialized Agents"
grep -q "6.*specialized.*agent\|6.*agent.*deploy" $file && echo "- [x] Agent count confirmed (6)" || echo "- [ ] Count missing"
grep -q "FIREWALL_CONFIG_AGENT" $file && echo "- [x] FIREWALL_CONFIG_AGENT" || echo "- [ ] Missing"
grep -q "ACL_ANALYSIS_AGENT" $file && echo "- [x] ACL_ANALYSIS_AGENT" || echo "- [ ] Missing"
grep -q "ZONE_POLICY_AGENT" $file && echo "- [x] ZONE_POLICY_AGENT" || echo "- [ ] Missing"
echo ""
echo "## Investigation"
grep -q "MCP.*server\|NETCONF\|SSH" $file && echo "- [x] MCP server queries" || echo "- [ ] MCP missing"
grep -q "Working.*List" $file && echo "- [x] Working lists" || echo "- [ ] Lists missing"
grep -q "Not Working.*List" $file && echo "- [x] Not Working lists" || echo "- [ ] Lists missing"
grep -q "Inter-Agent\|Collaboration" $file && echo "- [x] Agent collaboration" || echo "- [ ] Collaboration missing"
echo ""
echo "## Analysis & Resolution"
grep -q "Correlation.*Analysis" $file && echo "- [x] MRA correlation" || echo "- [ ] Correlation missing"
grep -q "Symptom.*vs.*cause\|SYMPTOM.*ROOT.*CAUSE" $file && echo "- [x] Symptom vs. cause table" || echo "- [ ] Table missing"
grep -q "Root Cause.*Analysis\|RCA" $file && echo "- [x] Clear RCA" || echo "- [ ] RCA missing"
echo ""
echo "## Implementation"  
grep -q "Permission.*Request\|User.*Approval" $file && echo "- [x] User permission request" || echo "- [ ] Permission missing"
grep -q "DEPLOYMENT_AGENT" $file && echo "- [x] DEPLOYMENT_AGENT" || echo "- [ ] Missing"
echo ""
echo "## Verification & Closure"
grep -q "VERIFICATION_AGENT" $file && echo "- [x] VERIFICATION_AGENT" || echo "- [ ] Missing"
grep -q "Final Report" $file && echo "- [x] Final report" || echo "- [ ] Report missing"
grep -q "CLOSED\|RESOLVED" $file && echo "- [x] Ticket closed" || echo "- [ ] Closure missing"
echo ""
grep -q "FW-8823" $file && grep -q "DEPLOYMENT_AGENT" $file && grep -q "VERIFICATION_AGENT" $file && \
echo "## ✅ COMPLIANCE: PASSED (All critical items present)" || \
echo "## ❌ COMPLIANCE: FAILED (Missing items)"
